[project]
name = "l1c"
version = "0.1.0.dev0"
description = "L1 language compiler bootstrap"
authors = [{ name = "gwz (googlielmo)", email = "googlielmo@gmail.com" }]
requires-python = ">=3.14"
dependencies = []

[tool.uv]
package = false

[tool.pytest.ini_options]
addopts = "-n auto"
testpaths = ["compiler/stage1_l0/tests"]
