# SPDX-License-Identifier: MIT OR Apache-2.0
# Copyright (c) 2025-2026 gwz

from dataclasses import dataclass
from typing import Callable
from l0_ast import EnumDecl, Expr, FuncDecl, LetDecl, StructDecl
from l0_signatures import EnumInfo, StructInfo
from l0_string_escape import encode_c_string_bytes
from l0_types import Type, FuncType
from l0_c_cleanup import CCleanup
from l0_c_names import CNames
from l0_c_state import CEmitterState
from l0_c_types import CTypes


@dataclass
class CDeclarations:
    """Translation-unit layout and top-level C declarations."""

    cleanup: CCleanup
    names: CNames
    state: CEmitterState
    types: CTypes

    def emit_section_comment(self, text: str) -> None:
        """Emit a decorative section comment.

        Args:
            text: The comment text.
        """
        self.state.out.emit(f"/* {text} */")

    def emit_module_comment(self, module_name: str) -> None:
        """Emit a module metadata comment.

        Args:
            module_name: The name of the module.
        """
        self.state.out.emit(f"/* Module: {module_name} */")

    def emit_module_separator(self, module_name: str) -> None:
        """Emit a decorative module separator.

        Args:
            module_name: The name of the module.
        """
        self.state.out.emit("/* -------------------------------- */")
        self.state.out.emit(f"/* Module: {module_name} */")
        self.state.out.emit("/* -------------------------------- */")

    def emit_unreachable_comment(self) -> None:
        """Emit an unreachable code comment for debugging."""
        self.state.out.emit("/* unreachable code here */")

    def emit_unreachable_marker(self, reason: str = "unreachable") -> None:
        """Emit a runtime panic call for unreachable code paths.

        Args:
            reason: Description of why the path is unreachable.
        """
        # escape reason string for C
        c_reason = encode_c_string_bytes(reason.encode("utf-8"))
        self.state.out.emit(f'L0_UNREACHABLE("{c_reason}");')

    def emit_header(self) -> None:
        """Emit C header boilerplate, SipHash implementation, and L0 runtime."""
        self.state.out.emit("/* Generated by l0c, the Dea/L0 compiler. Do not edit. */")
        self.state.out.emit()
        self.state.out.emit("#include <stdint.h>")
        self.state.out.emit("#include <stdbool.h>")
        self.state.out.emit("#include <stddef.h>")
        self.state.out.emit()
        self.state.out.emit("/* Include SipHash runtime implementation in main translation unit */")
        self.state.out.emit("#define SIPHASH_IMPLEMENTATION")
        self.state.out.emit('#include "dea_siphash.h"')
        self.state.out.emit()
        self.state.out.emit("/* L0 runtime header */")
        if self.state.analysis.context.trace_arc:
            self.state.out.emit("#define L0_TRACE_ARC 1")
        if self.state.analysis.context.trace_memory:
            self.state.out.emit("#define L0_TRACE_MEMORY 1")
        if self.state.analysis.context.rt_unchecked:
            self.state.out.emit("#define L0_RT_UNCHECKED 1")
        if self.state.analysis.context.rt_check_basic:
            self.state.out.emit("#define L0_RT_CHECK_BASIC 1")
        self.state.out.emit('#include "l0_runtime.h"')
        self.state.out.emit()

    def emit_forward_decls(self) -> None:
        """Emit forward declarations for all structs and enums in compilation unit."""
        self.state.out.emit("/* Forward declarations */")

        for module in self.state.analysis.cu.modules.values():
            for decl in module.decls:
                if isinstance(decl, StructDecl):
                    c_name = self.names.mangle_struct_name(module.name, decl.name)
                    self.state.out.emit(f"struct {c_name};")
                elif isinstance(decl, EnumDecl):
                    c_name = self.names.mangle_enum_name(module.name, decl.name)
                    self.state.out.emit(f"struct {c_name};")

        self.state.out.emit()

    def emit_struct(self, module_name: str, decl: StructDecl, struct_info: StructInfo) -> None:
        """Emit a complete C struct definition.

        Args:
            module_name: Name of the module.
            decl: StructDecl AST node.
            struct_info: Resolved type information for the struct.
        """
        c_name = self.names.mangle_struct_name(module_name, decl.name)
        guard = f"L0_DEFINED_{c_name}"
        self.state.out.emit(f"#ifndef {guard}")
        self.state.out.emit(f"#define {guard}")
        self.state.out.emit(f"struct {c_name} {{")
        self.state.out.indent()

        # Emit fields
        for field_info in struct_info.fields:
            c_type = self.types.emit_type(field_info.type)
            self.state.out.emit(f"{c_type} {field_info.name};")

        if not struct_info.fields:
            # Empty struct - add dummy field, as empty structs are not allowed in standard C (C99)
            self.state.out.emit("char __dummy__;")

        self.state.out.dedent()
        self.state.out.emit("};")
        self.state.out.emit("#endif")
        self.state.out.emit()

    def emit_enum(self, module_name: str, decl: EnumDecl, enum_info: EnumInfo) -> None:
        """Emit an L0 enum as a C tagged union.

        Args:
            module_name: Name of the module.
            decl: EnumDecl AST node.
            enum_info: Resolved type information for the enum.

        Raises:
            InternalCompilerError: If variant information is missing.
        """
        c_name = self.names.mangle_enum_name(module_name, decl.name)
        guard = f"L0_DEFINED_{c_name}"
        tag_enum_name = f"{c_name}_tag"

        self.state.out.emit(f"#ifndef {guard}")
        self.state.out.emit(f"#define {guard}")

        # Emit tag enum
        self.state.out.emit(f"enum {tag_enum_name} {{")
        self.state.out.indent()

        for variant in decl.variants:
            tag_value = f"{c_name}_{variant.name}"
            self.state.out.emit(f"{tag_value},")

        self.state.out.dedent()
        self.state.out.emit("};")
        self.state.out.emit()

        # Emit tagged union struct
        self.state.out.emit(f"struct {c_name} {{")
        self.state.out.indent()
        self.state.out.emit(f"enum {tag_enum_name} tag;")

        # Emit union of variant payloads
        self.state.out.emit("union {")
        self.state.out.indent()

        for variant in decl.variants:
            variant_info = enum_info.variants.get(variant.name)
            if variant_info is None:
                self.state.ice(f"[ICE-1271] missing VariantInfo for {module_name}.{decl.name}.{variant.name}", variant)

            if not variant_info.field_types:
                # Empty variant - still need a struct for uniform access
                self.state.out.emit(f"struct {{ char __dummy__; }} {variant.name};")
            else:
                # Variant with fields
                field_decls = []
                for field_, ftype in zip(variant.fields, variant_info.field_types):
                    c_type = self.types.emit_type(ftype)
                    field_decls.append(f"{c_type} {field_.name}")

                fields_str = "; ".join(field_decls) + ";"
                self.state.out.emit(f"struct {{ {fields_str} }} {variant.name};")

        self.state.out.dedent()
        self.state.out.emit("} data;")

        self.state.out.dedent()
        self.state.out.emit("};")
        self.state.out.emit("#endif")
        self.state.out.emit()

    def emit_let_declaration(self, module_name: str, decl: LetDecl, let_type: Type, let_initializer_callback: Callable[[Expr, Type], str]) -> None:
        """Emit a single top-level let declaration as a static variable.

        Args:
            module_name: Module containing the let.
            decl: Let declaration AST node.
            let_type: Resolved type of the let.
            let_initializer_callback: Callback to emit initializer expression string.
        """
        c_type = self.types.emit_type(let_type)
        c_name = self.names.mangle_let_name(module_name, decl.name)
        c_init = let_initializer_callback(decl.value, let_type)
        self.state.out.emit(f"static {c_type} {c_name} = {c_init};")

    def emit_top_level_let_cleanup(self) -> None:
        """Emit final cleanup for ARC-managed top-level lets before process exit."""
        if self.state.analysis is None or self.state.analysis.cu is None:
            return
        for module in self.state.analysis.cu.modules.values():
            for decl in module.decls:
                if not isinstance(decl, LetDecl):
                    continue
                let_type = self.state.analysis.let_types.get((module.name, decl.name))
                if let_type is None or not self.state.analysis.has_arc_data(let_type):
                    continue
                self.cleanup.emit_value_cleanup(self.names.mangle_let_name(module.name, decl.name), let_type)

    def emit_function_declaration(self, module_name: str, decl: FuncDecl, func_type: FuncType) -> None:
        """Emit a single function declaration signature.

        Args:
            module_name: Name of the module.
            decl: FuncDecl AST node.
            func_type: Resolved signature of the function.
        """
        # CRITICAL: extern functions are NOT mangled - they're the FFI boundary
        if decl.is_extern:
            # Wrap extern function names in parens to prevent macro expansion
            # (e.g. if an extern function is implemented as a macro in the C runtime)
            c_name = f"({decl.name})"
        else:
            c_name = self.names.mangle_function_name(module_name, decl.name)

        c_return_type = self.types.emit_type(func_type.result)

        # Parameter list
        if not func_type.params:
            params_str = "void"
        else:
            param_strs = []
            for param, ptype in zip(decl.params, func_type.params):
                c_ptype = self.types.emit_type(ptype)
                c_param_name = self.names.mangle_identifier(param.name)
                param_strs.append(f"{c_ptype} {c_param_name}")
            params_str = ", ".join(param_strs)

        self.state.out.emit(f"{c_return_type} {c_name}({params_str});")

    def emit_function_definition_header(self, module_name: str, decl: FuncDecl, func_type: FuncType) -> None:
        """Emit function definition header (signature and opening brace).

        Args:
            module_name: Name of the module.
            decl: FuncDecl AST node.
            func_type: Resolved signature of the function.
        """
        c_name = self.names.mangle_function_name(module_name, decl.name)
        c_return_type = self.types.emit_type(func_type.result)

        # Parameter list
        if not func_type.params:
            params_str = "void"
        else:
            param_strs = []
            for param, ptype in zip(decl.params, func_type.params):
                c_ptype = self.types.emit_type(ptype)
                c_param_name = self.names.mangle_identifier(param.name)
                param_strs.append(f"{c_ptype} {c_param_name}")
            params_str = ", ".join(param_strs)

        # Function header
        self.state.out.emit(f"{c_return_type} {c_name}({params_str})")
        self.state.out.emit("{")
        self.state.out.indent()

    def emit_function_definition_footer(self) -> None:
        """Emit function definition footer (closing brace)."""
        self.state.out.dedent()
        self.state.out.emit("}")
        self.state.out.emit()

    def emit_main_wrapper(self, entry_module: str, func_type: FuncType) -> None:
        """Emit C main() wrapper that calls the L0 entry function.

        Args:
            entry_module: Name of the entry module.
            func_type: Resolved signature of the L0 main function.
        """
        self.state.out.emit("/* C entry point wrapper */")
        self.state.out.emit(f"int main(int argc, char **argv)")
        self.state.out.emit("{")
        self.state.out.indent()

        # Take care of argc/argv
        self.state.out.emit("_rt_init_args(argc, argv);")

        # Determine return type and call
        mangled_name = self.names.mangle_function_name(entry_module, "main")
        c_return_type = self.types.emit_type(func_type.result)

        if c_return_type == "l0_int":
            self.state.out.emit(f"int l0_exit_code = (int) {mangled_name}();")
        elif c_return_type == "bool":
            self.state.out.emit(f"bool result = {mangled_name}();")
            self.state.out.emit("int l0_exit_code = result ? 0 : 1;")
        else:
            self.state.out.emit(f"{mangled_name}();")
            self.state.out.emit("int l0_exit_code = 0;")

        self.emit_top_level_let_cleanup()
        self.state.out.emit("return l0_exit_code;")
        self.state.out.dedent()
        self.state.out.emit("}")
        self.state.out.emit()
